name: "Build Test Publish"

on:
  workflow_dispatch:
    # Just in case

  pull_request:
    branches: [main]

  push:
    branches: [main]
    tags:
      - 'v*'
      - "!**-test"
      - "!**-dev"


jobs:
  build-modules:
    uses: infinity-swap/ci-wf/.github/workflows/build-n-test.yml@main
    with:
      skip-test: ${{ github.ref_type == 'tag' }}
      output-artifact: is20-modules
      test-script: |
        cargo test
    secrets:
      gh_token: ${{ secrets.GH_PKG_TOKEN }}
      gh_login: ${{ secrets.GH_PKG_LOGIN }}
  

  publishing:
    needs: [build-modules]
    uses: infinity-swap/ci-wf/.github/workflows/publish-wrapped-artifact.yml@main
    with:
      input-artifact: is20-modules
      output-image-name: is20-modules
      add-prefix-to-files: is20_
      # Condition to add latest tag
      output-image-tag-latest: ${{ github.ref_type == 'branch' && github.ref == 'refs/heads/main' }}
      # Condition to publish docker image
      push-image: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}

    secrets:
      gh_token: ${{ secrets.GH_PKG_TOKEN }}
      gh_login: ${{ secrets.GH_PKG_LOGIN }}
