name: Deploy

on:
  push:
    tags:
      - "v**-test"
      - "v**-dev"

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: us-central1-docker.pkg.dev/dfx-server/dfx-containers/ci
      credentials:
        username: _json_key
        password: ${{ secrets.GCP_DOCKER_KEY }}

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}

      - name: setup config for dev net
        run: |
          echo "UPLOAD_DIR=devnet" >> $GITHUB_ENV
        if: ${{ endsWith(github.ref_name, '-dev') }}

      - name: setup config for test net
        run: |
          echo "UPLOAD_DIR=testnet" >> $GITHUB_ENV
        if: ${{ endsWith(github.ref_name, '-test') }}

      - name: Build canisters and candid files
        run: |
          bash scripts/build.sh
          mkdir -p ${UPLOAD_DIR}
          cp src/candid/token.did src/factory/src/token.wasm ${UPLOAD_DIR}
          cp src/candid/factory.did ${UPLOAD_DIR}/token-factory.did
          cp target/wasm32-unknown-unknown/release/factory-opt.wasm ${UPLOAD_DIR}/token-factory.wasm

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.NET_GCP_COMPUTE_SA_JSON_KEY }}"

      - id: "upload-folder"
        uses: "google-github-actions/upload-cloud-storage@v0"
        with:
          path: ${{ env.UPLOAD_DIR }}
          destination: ${{ secrets.NET_BUCKET_NAME }}
